CREATE TABLE FUNCIONARIO(
CPF VARCHAR(11) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
NOME VARCHAR(50),
ENDERECO VARCHAR(100),
TIPOFUNCIONARIO VARCHAR(3) NOT NULL,
CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CPF),
CONSTRAINT UK_FUNCIONARIO UNIQUE(EMAIL),
CONSTRAINT CK1_FUNCIONARIO CHECK(TIPOFUNCIONARIO IN('adm','vnd')));

CREATE TABLE CLIENTE(
CPFCLIENTE VARCHAR(11) NOT NULL,
NOMECLIENTE VARCHAR(50),
TELEFONECLIENTE VARCHAR(20),
EMAILCLIENTE VARCHAR(50),
CONSTRAINT PK_CLIENTE PRIMARY KEY(CPFCLIENTE));

CREATE TABLE FILME(
IDFILME INT NOT NULL,
NOME VARCHAR(50),
CLASSIFICACAO VARCHAR(20),
SINOPSE VARCHAR(100),
GENERO VARCHAR(20),
CONSTRAINT PK_FILME PRIMARY KEY(IDFILME),
CONSTRAINT CK_FILME CHECK(CLASSIFICACAO>=0));

CREATE TABLE SESSAO(
VALORINTEIRA VARCHAR(10),
VALORMEIA VARCHAR(10),
DATA VARCHAR(10),
HORA VARCHAR(5),
SALA VARCHAR(20),
IDSESSAO INT NOT NULL,
IDFILMEPERTENCE INT NOT NULL,
CONSTRAINT PK_SESSAO PRIMARY KEY(IDSESSAO),
CONSTRAINT FK_SESSAO FOREIGN KEY(IDFILMEPERTENCE) REFERENCES FILME(IDFILME) 
ON DELETE CASCADE);

CREATE TABLE INGRESSO(
IDINGRESSO INT NOT NULL,
CPFCLIENTECOMPRA VARCHAR(11),
CPFFUNCIONARIOVENDA VARCHAR(11),
IDSESSAOPERTENCE INT NOT NULL,
CONSTRAINT PK_INGRESSO PRIMARY KEY(IDINGRESSO),
CONSTRAINT FK1_INRESSO FOREIGN KEY(CPFCLIENTECOMPRA) REFERENCES CLIENTE(CPFCLIENTE) 
ON DELETE SET NULL,
CONSTRAINT FK2_INRESSO FOREIGN KEY(CPFFUNCIONARIOVENDA) REFERENCES FUNCIONARIO(CPF) 
ON DELETE SET NULL);